name: 'Feature Insertion'
description: Issues for new features or enhancements to existing features.
title: '`[FEAT]` - Title'
projects: ['odavibatista/5']
assignees: 'odavibatista'

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: What is this feature related to?
      options:
        - API Integration
        - Authentication
        - Components
        - Optimizations
        - Pages
        - Refactoring
        - Styling
        - Testing
      multiple: true

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: How risky is this feature?
      options:
        - label: Riskless
          required: false
        - label: Low
          required: false
        - label: Medium
          required: false
        - label: High
          required: false
